-- AlterEnum
ALTER TYPE "CategoriaSoporte" ADD VALUE 'ELECTRICO_ENERGIA';
ALTER TYPE "CategoriaSoporte" ADD VALUE 'CLIMATIZACION';
ALTER TYPE "CategoriaSoporte" ADD VALUE 'IMPRESION';
ALTER TYPE "CategoriaSoporte" ADD VALUE 'SEGURIDAD_FISICA';
